repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.21
    hooks:
      - id: uv-lock
    
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.4
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --select I, --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi ]
